# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-04 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0014_auto_20180413_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=150)),
                ('metadata', jsonfield.fields.JSONField(blank=True, null=True)),
                ('stripe_account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinax_stripe.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='plan_products', related_query_name='plan_product', to='pinax_stripe.Plan'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('stripe_id', 'stripe_account')]),
        ),
    ]
