# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-28 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0019_auto_20181123_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='billing_scheme',
            field=models.CharField(default='per_unit', max_length=15),
        ),
        migrations.AddField(
            model_name='plan',
            name='usage_type',
            field=models.CharField(default='licensed', max_length=15),
        ),
    ]
