# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-10 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0020_auto_20191128_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=191, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('subscription_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinax_stripe.SubscriptionItem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
