# Generated by Django 4.1.7 on 2023-03-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0022_auto_20191212_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='verification_fields_needed',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='captured',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='disputed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='outcome',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='paid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='refunded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='valid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='validated_message',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='webhook_message',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='attempted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
